import { styleTags, tags as t } from "@lezer/highlight"

export const rHighlight = styleTags({
  "if else for while repeat function break next in": t.controlKeyword,
  "TRUE": t.bool,
  "FALSE": t.bool,
  "NA NA_integer_ NA_real_ NA_character_ NA_complex_": t.null,
  "NULL": t.null,
  "Inf NaN": t.number,
  "Dots": t.special(t.variableName),
  "PipePlaceholder": t.special(t.variableName),
  "Identifier": t.variableName,
  "Backtick": t.variableName,
  "Number": t.number,
  "String RawString": t.string,
  "Comment": t.lineComment,
  "ArithOp": t.arithmeticOperator,
  "CompareOp": t.compareOperator,
  "LogicOp": t.logicOperator,
  "AssignOp": t.definitionOperator,
  "NamespaceOp": t.derefOperator,
  "MemberOp": t.derefOperator,
  "SpecialOp": t.operatorKeyword,
  "~": t.operator,
  "?": t.operator,
  "|>": t.controlOperator,
  "Call/Identifier": t.function(t.variableName),
  "Call/Backtick": t.function(t.variableName),
  "NamespaceExpr/Identifier NamespaceExpr/Backtick NamespaceExpr/String": t.function(t.variableName),
  "MemberExpr/Identifier MemberExpr/Backtick MemberExpr/String": t.propertyName,
  "ArgName/Identifier ArgName/Backtick ArgName/String": t.propertyName,
  "ParamName/Identifier ParamName/Backtick": t.propertyName,
  "ParenL ParenR ContinueParenL": t.paren,
  "BracketR ContinueBracketL ContinueDBracketL": t.squareBracket,
  "BraceL BraceR": t.brace,
  ",": t.separator,
  "; InsertedSemi": t.separator,
  "::": t.derefOperator,
  ":::": t.derefOperator,
  "$ @": t.derefOperator
})
